### ISSUE TITLE
MySQL实现远程登录

### ISSUE THREAD

**Issue by itcuihao** [itcuihao/blog#123]
```
mysql> select * from user where user='root'\G
*************************** 1. row ***************************
                  Host: localhost
                  User: root
           Select_priv: Y
           Insert_priv: Y
           Update_priv: Y
           Delete_priv: Y
           Create_priv: Y
             Drop_priv: Y
           Reload_priv: Y
         Shutdown_priv: Y
          Process_priv: Y
             File_priv: Y
            Grant_priv: Y
       References_priv: Y
            Index_priv: Y
            Alter_priv: Y
          Show_db_priv: Y
            Super_priv: Y
 Create_tmp_table_priv: Y
      Lock_tables_priv: Y
          Execute_priv: Y
       Repl_slave_priv: Y
      Repl_client_priv: Y
      Create_view_priv: Y
        Show_view_priv: Y
   Create_routine_priv: Y
    Alter_routine_priv: Y
      Create_user_priv: Y
            Event_priv: Y
          Trigger_priv: Y
Create_tablespace_priv: Y
              ssl_type: 
            ssl_cipher: 
           x509_issuer: 
          x509_subject: 
         max_questions: 0
           max_updates: 0
       max_connections: 0
  max_user_connections: 0
                plugin: caching_sha2_password
 authentication_string: $A$005$2t=<W>W9V|.JBuK./ntmQrgqFcjO/zcX0wS9chl09mf/55rkP2j5tonUIC
      password_expired: N
 password_last_changed: 2018-05-25 19:55:57
     password_lifetime: NULL
        account_locked: N
      Create_role_priv: Y
        Drop_role_priv: Y
Password_reuse_history: NULL
   Password_reuse_time: NULL
1 row in set (0.00 sec)

mysql> 
```

给root授权
```
grant all on *.* to 'root'@'%';
flush privileges;
```

登录报错：
```
Can't connect to MySQL server on '127.0.0.1' (111)
```
mysql8 用了新的加密方式[caching_sha2_password](https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html)，workbench貌似还没有支持。
修改密码：

```
alter user 'root'@'%' identified with mysql_native_password by 'password'
```
